# These provide us a way of injecting environment variables into the pods
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: development
data:
  POSTGRES_DB: "kubetutorial101"
  POSTGRES_USER: "postgres"
  RUN_IN_PRODUCTION: "False"


      
